export default [
  {
    id: 1,
    postedOn: '2025-07-01',
    title: 'iOS Developer',
    company: 'Apple Inc.',
    type: 'Full Time',
    experience: 'Junior Level',
    location: 'In-Office',
    skills: ['Swift', 'UIKit', 'CoreML'],
    job_link: 'https://www.apple.com/careers/in/'
  },
  {
    id: 2,
    postedOn: '2025-07-02',
    title: 'Android Developer',
    company: 'Samsung',
    type: 'Contract',
    experience: 'Mid Level',
    location: 'Remote',
    skills: ['Kotlin', 'Jetpack Compose', 'MVVM'],
    job_link: 'https://careers.samsung.com/'
  },
  {
    id: 3,
    postedOn: '2025-07-03',
    title: 'Frontend Developer',
    company: 'Meta',
    type: 'Part Time',
    experience: 'Senior Level',
    location: 'Hybrid',
    skills: ['ReactJS', 'Next.js', 'Tailwind CSS'],
    job_link: 'https://www.metacareers.com/'
  },
  {
    id: 4,
    postedOn: '2025-07-04',
    title: 'Backend Developer',
    company: 'Netflix',
    type: 'Full Time',
    experience: 'Mid Level',
    location: 'Remote',
    skills: ['Node.js', 'MongoDB', 'Redis'],
    job_link: 'https://jobs.netflix.com/'
  },
  {
    id: 5,
    postedOn: '2025-07-05',
    title: 'Developer Advocate',
    company: 'GitHub',
    type: 'Full Time',
    experience: 'Senior Level',
    location: 'Remote',
    skills: ['Public Speaking', 'Open Source', 'Docs Writing'],
    job_link: 'https://github.com/about/careers'
  },
  {
    id: 6,
    postedOn: '2025-07-06',
    title: 'Frontend Developer',
    company: 'Adobe',
    type: 'Contract',
    experience: 'Fresher',
    location: 'Hybrid',
    skills: ['HTML', 'CSS', 'JavaScript'],
    job_link: 'https://www.adobe.com/careers.html'
  },
  {
    id: 7,
    postedOn: '2025-07-07',
    title: 'Android Developer',
    company: 'OnePlus',
    type: 'Full Time',
    experience: 'Junior Level',
    location: 'In-Office',
    skills: ['Java', 'XML', 'Android SDK'],
    job_link: 'https://www.oneplus.com/careers'
  },
  {
    id: 8,
    postedOn: '2025-07-08',
    title: 'iOS Developer',
    company: 'Paytm',
    type: 'Part Time',
    experience: 'Fresher',
    location: 'Remote',
    skills: ['SwiftUI', 'Combine', 'Core Data'],
    job_link: 'https://paytm.com/about-us/opportunities/'
  },
  {
    id: 9,
    postedOn: '2025-07-09',
    title: 'Backend Developer',
    company: 'Zerodha',
    type: 'Full Time',
    experience: 'Junior Level',
    location: 'In-Office',
    skills: ['Django', 'PostgreSQL', 'APIs'],
    job_link: 'https://zerodha.com/careers/'
  },
  {
    id: 10,
    postedOn: '2025-07-10',
    title: 'Developer Advocate',
    company: 'Stripe',
    type: 'Contract',
    experience: 'Mid Level',
    location: 'Hybrid',
    skills: ['Community Building', 'Python', 'Public Demos'],
    job_link: 'https://stripe.com/jobs'
  },
  {
    id: 11,
    postedOn: '2025-07-11',
    title: 'Frontend Developer',
    company: 'Google',
    type: 'Full Time',
    experience: 'Mid Level',
    location: 'Remote',
    skills: ['Vue.js', 'Nuxt.js', 'SCSS'],
    job_link: 'https://careers.google.com/'
  },
  {
    id: 12,
    postedOn: '2025-07-12',
    title: 'iOS Developer',
    company: 'Swiggy',
    type: 'Contract',
    experience: 'Senior Level',
    location: 'In-Office',
    skills: ['Objective-C', 'Swift', 'REST APIs'],
    job_link: 'https://careers.swiggy.com/'
  },
  {
    id: 13,
    postedOn: '2025-07-13',
    title: 'Android Developer',
    company: 'Ola Electric',
    type: 'Part Time',
    experience: 'Fresher',
    location: 'Hybrid',
    skills: ['Kotlin', 'Firebase', 'MVVM'],
    job_link: 'https://olaelectric.com/careers'
  },
  {
    id: 14,
    postedOn: '2025-07-14',
    title: 'Backend Developer',
    company: 'RedBus',
    type: 'Full Time',
    experience: 'Mid Level',
    location: 'Remote',
    skills: ['Spring Boot', 'MySQL', 'REST'],
    job_link: 'https://www.redbus.in/info/careers'
  },
  {
    id: 15,
    postedOn: '2025-07-15',
    title: 'Developer Advocate',
    company: 'Hashnode',
    type: 'Full Time',
    experience: 'Junior Level',
    location: 'Remote',
    skills: ['DevRel', 'Blogging', 'Open Source'],
    job_link: 'https://hashnode.com/jobs'
  },
  {
    id: 16,
    postedOn: '2025-07-16',
    title: 'iOS Developer',
    company: 'Uber',
    type: 'Contract',
    experience: 'Mid Level',
    location: 'Hybrid',
    skills: ['SwiftUI', 'Combine', 'XCTest'],
    job_link: 'https://www.uber.com/global/en/careers/'
  },
  {
    id: 17,
    postedOn: '2025-07-17',
    title: 'Android Developer',
    company: 'BYJU\'S',
    type: 'Full Time',
    experience: 'Senior Level',
    location: 'In-Office',
    skills: ['Android Jetpack', 'MVVM', 'Coroutines'],
    job_link: 'https://byjus.com/careers/'
  },
  {
    id: 18,
    postedOn: '2025-07-18',
    title: 'Frontend Developer',
    company: 'CRED',
    type: 'Part Time',
    experience: 'Fresher',
    location: 'Remote',
    skills: ['ReactJS', 'Framer Motion', 'CSS Modules'],
    job_link: 'https://cred.club/careers'
  },
  {
    id: 19,
    postedOn: '2025-07-19',
    title: 'Backend Developer',
    company: 'Amazon',
    type: 'Full Time',
    experience: 'Senior Level',
    location: 'Hybrid',
    skills: ['Java', 'AWS', 'Microservices'],
    job_link: 'https://www.amazon.jobs/'
  },
  {
    id: 20,
    postedOn: '2025-07-20',
    title: 'Developer Advocate',
    company: 'OpenAI',
    type: 'Contract',
    experience: 'Mid Level',
    location: 'Remote',
    skills: ['AI Tools', 'Public Speaking', 'Blogging'],
    job_link: 'https://openai.com/careers'
  },
  {
    id: 21,
    postedOn: '2025-07-21',
    title: 'Frontend Developer',
    company: 'Freshworks',
    type: 'Full Time',
    experience: 'Junior Level',
    location: 'In-Office',
    skills: ['Angular', 'TypeScript', 'Bootstrap'],
    job_link: 'https://www.freshworks.com/company/careers/'
  },
  {
    id: 22,
    postedOn: '2025-07-22',
    title: 'iOS Developer',
    company: 'PhonePe',
    type: 'Part Time',
    experience: 'Fresher',
    location: 'Hybrid',
    skills: ['UIKit', 'MapKit', 'Swift'],
    job_link: 'https://www.phonepe.com/careers/'
  },
  {
    id: 23,
    postedOn: '2025-07-23',
    title: 'Android Developer',
    company: 'Dream11',
    type: 'Full Time',
    experience: 'Mid Level',
    location: 'Remote',
    skills: ['Kotlin', 'Room DB', 'Retrofit'],
    job_link: 'https://dream11careers.com/'
  },
  {
    id: 24,
    postedOn: '2025-07-24',
    title: 'Backend Developer',
    company: 'Nykaa',
    type: 'Contract',
    experience: 'Junior Level',
    location: 'In-Office',
    skills: ['PHP', 'Laravel', 'MySQL'],
    job_link: 'https://careers.nykaa.com/'
  },
  {
    id: 25,
    postedOn: '2025-07-25',
    title: 'Developer Advocate',
    company: 'Dev.to',
    type: 'Full Time',
    experience: 'Senior Level',
    location: 'Remote',
    skills: ['Community Management', 'Speaking', 'Technical Writing'],
    job_link: 'https://dev.to/devteam/hiring'
  }
];
